from typing import Any, Dict
from .row import CqlRow

class Session:
    async def execute(self, request: str) -> RequestResult: ...

class RowFactory:
    def __init__(self) -> None: ...
    def build(self, column: CqlRow) -> Dict[str, Any]: ...

class RowsResult:
    def __next__(self) -> Any: ...
    def __iter__(self) -> RowsResult: ...

class RequestResult:
    def __str__(self) -> str: ...
    def create_rows_result(self, factory: Any | None = None) -> RowsResult: ...
